version: '3'
services:
  sab:
    image: "sabnzbd/sabnzbd"
    ports:
         - 8080:8080
    volumes:
         - ./sab:/datadir
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
  sonarr:
    image: "linuxserver/sonarr"
    ports:
         - 8989:8989
    volumes:
         - ./sonarr:/config
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
  couchpotato:
    image: "linuxserver/couchpotato"
    ports:
         - 9090:9090
    volumes:
         - ./couch:/config